(package "packaging"
         "0.0.0"
         "Packaging for Eask CLI")

(website-url "https://github.com/emacs-eask/packaging")
(keywords "packaging" "tools")

(script "test" "echo \"Error: no test specified\" && exit 1")
(script "brew-update" "eask load scripts/brew-update.el")
(script "scoop-update" "eask load scripts/scoop-update.el")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "26.1")
(depends-on "github-tags")
