name: eask-cli
version: 0.8.6
summary: CLI for building, runing, testing, and managing your Emacs Lisp dependencies
description: |
  Eask was built to be used as a package development tool in your Elisp packages.
  But now, it can be used as a dev tool for Elisp packages, dependency management
  for your configuration, or run elisp programs for all other purposes.
license: GPL-3.0

grade: stable
base: core20
confinement: strict

apps:
  eask-cli:
    command: bin/eask

parts:
  eask-cli:
    plugin: npm
    npm-node-version: 16.15.0
    source: https://github.com/emacs-eask/cli
    source-type: git
