name: Choco Install

on:
  push:
    branches:
      - master
    paths:
      - 'chocolatey/**'
      - '**.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EMACS_VER: 30.2

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.expose-ver.outputs.VERSION }}
    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ env.EMACS_VER }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v5

    - name: Expose Version
      id: expose-ver
      run: |
        eask install-deps --dev
        VERSION=$(eask load scripts/latest-tag.el)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "$VERSION"

  build:
    needs: [get-version]
    runs-on: windows-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    steps:
    - name: Install Chocolatey
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - uses: actions/checkout@v5

    - name: Install Eask CLI
      working-directory: ./chocolatey/
      run: |
        choco pack
        choco install eask-cli.${{ env.VERSION }}.nupkg --debug --verbose --source .

    - run: eask --version
