name: Choco Install

on:
  push:
    branches:
      - master
    paths:
      - 'chocolatey/**'
      - '**.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-version:
      uses: emacs-eask/packaging/.github/workflows/share/get_version.yml@master

  build:
    needs: [get-version]
    runs-on: windows-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    steps:
    - name: Install Chocolatey
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - uses: actions/checkout@v5

    - name: Install Eask CLI
      working-directory: ./chocolatey/
      run: |
        choco pack
        choco install eask-cli --version="${{ env.VERSION }}" --source="."

    - run: eask --version
